[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["google-spreadsheet", "ky"]
