require('dotenv').config();
const express = require('express');
const multer = require('multer');
const cors = require('cors');
const path = require('path');
const { Resend } = require('resend');
const { GoogleSpreadsheet } = require('google-spreadsheet');
const { JWT } = require('google-auth-library');

const app = express();
const PORT = 3000;

// Resend setup
const resend = new Resend(process.env.RESEND_API_KEY);

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// Multer for file uploads (store in memory for email attachment)
const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB max
  fileFilter: (req, file, cb) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'application/pdf'];
    if (allowed.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error('Only images and PDF files are allowed'), false);
    }
  }
});

// Build admin email HTML
function buildAdminEmailHTML(data) {
  const fieldRows = [
    ['Full Name', data.fullName],
    ['Email', data.email],
    ['Phone', data.phone || 'Not provided'],
    ['Gender', data.gender],
    ['Country', data.country || 'Not provided'],
    ['Age', data.age || 'Not provided'],
    ['30s Reel Price (From)', data.price30From || 'Infinite'],
    ['30s Reel Price (Till)', data.price30Till || 'Infinite'],
    ['60s Reel Price (From)', data.price60From || 'Infinite'],
    ['60s Reel Price (Till)', data.price60Till || 'Infinite'],
  ];

  const rows = fieldRows.map(([label, value]) => `
    <tr>
      <td style="padding: 12px 16px; font-weight: 600; color: #0A0A0F; background: #FAF9F6; border-bottom: 1px solid #f0ece6; width: 200px; vertical-align: top; font-size: 14px;">${label}</td>
      <td style="padding: 12px 16px; color: #333; border-bottom: 1px solid #f0ece6; font-size: 14px; line-height: 1.6;">${value || '—'}</td>
    </tr>
  `).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head><meta charset="UTF-8"></head>
  <body style="margin: 0; padding: 0; background: #f4f1ec; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;">
    <div style="max-width: 640px; margin: 0 auto; padding: 40px 20px;">
      <!-- Header -->
      <div style="text-align: center; padding: 32px 0 24px;">
        <img src="https://res.cloudinary.com/dxd79mrse/image/upload/v1781437518/Idyll_Productions_Black_aburqi.png" alt="Idyll Productions" style="height: 40px;" />
      </div>
      
      <!-- Main Card -->
      <div style="background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 2px 16px rgba(0,0,0,0.06);">
        <!-- Orange Banner -->
        <div style="background: linear-gradient(135deg, #FF7A3A, #FF6B35, #FFB86A); padding: 28px 32px;">
          <h1 style="margin: 0; color: #fff; font-size: 22px; font-weight: 700;">New UGC Creator Application</h1>
          <p style="margin: 8px 0 0; color: rgba(255,255,255,0.9); font-size: 14px;">Received on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>
        </div>
        
        <!-- Table -->
        <table style="width: 100%; border-collapse: collapse;">
          ${rows}
        </table>

        ${data.hasAttachment ? `
        <div style="padding: 16px 16px 20px; background: #FAF9F6; border-top: 1px solid #f0ece6;">
          <p style="margin: 0; font-size: 13px; color: #666;">📎 Photo/Resume attached to this email</p>
        </div>` : ''}
      </div>

      <!-- Footer -->
      <div style="text-align: center; padding: 24px 0 0;">
        <p style="margin: 0; font-size: 11px; color: #999;">This email was generated by the Idyll Productions Hiring System</p>
        <p style="margin: 4px 0 0; font-size: 11px; color: #999;">© 2026 Idyll Productions. All rights reserved.</p>
      </div>
    </div>
  </body>
  </html>`;
}

// Build applicant confirmation email HTML
function buildConfirmationEmailHTML(name) {
  return `
  <!DOCTYPE html>
  <html>
  <head><meta charset="UTF-8"></head>
  <body style="margin: 0; padding: 0; background: #f4f1ec; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;">
    <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
      <!-- Header -->
      <div style="text-align: center; padding: 32px 0;">
        <img src="https://res.cloudinary.com/dxd79mrse/image/upload/v1781445552/idyll-productions-orange_q6o4ap.png" alt="Idyll Productions" style="height: 44px;" />
      </div>
      
      <!-- Main Card -->
      <div style="background: #ffffff; border-radius: 16px; padding: 40px 36px; box-shadow: 0 2px 16px rgba(0,0,0,0.06);">
        <!-- Orange accent line -->
        <div style="width: 48px; height: 4px; background: linear-gradient(90deg, #FF6B35, #FFB86A); border-radius: 2px; margin-bottom: 28px;"></div>
        
        <h1 style="margin: 0 0 24px; font-size: 24px; font-weight: 700; color: #0A0A0F;">Application Received</h1>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">Hello <strong>${name}</strong>,</p>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">Thank you for applying to become a UGC Creator with <strong>Idyll Productions</strong>.</p>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">We appreciate the time and effort you took to submit your application. Our team will carefully review your profile and keep it in our creator database.</p>
        
        <p style="margin: 0 0 16px; font-size: 15px; line-height: 1.7; color: #333;">Whenever we have a brand campaign or collaboration that matches your profile and content style, we'll reach out to you using the contact details you provided in your application.</p>
        
        <p style="margin: 0 0 28px; font-size: 15px; line-height: 1.7; color: #333;">Thank you once again for your valuable time. We look forward to the opportunity to work with you.</p>
        
        <div style="border-top: 1px solid #f0ece6; padding-top: 24px;">
          <p style="margin: 0; font-size: 15px; color: #333;">Regards,</p>
          <p style="margin: 4px 0 0; font-size: 15px; font-weight: 700; color: #0A0A0F;">HR Team</p>
          <p style="margin: 4px 0 0; font-size: 15px; color: #333;">Idyll Productions</p>
        </div>
      </div>

      <!-- Footer -->
      <div style="text-align: center; padding: 28px 0 0;">
        <div style="width: 100%; height: 3px; background: linear-gradient(90deg, #FF6B35, #FFB86A, #FF6B35); border-radius: 2px; margin-bottom: 20px;"></div>
        <p style="margin: 0; font-size: 11px; color: #999;">© 2026 Idyll Productions. All rights reserved.</p>
        <p style="margin: 4px 0 0; font-size: 11px; color: #bbb;">This is an automated confirmation email. Please do not reply.</p>
      </div>
    </div>
  </body>
  </html>`;
}

// API: Submit application
app.post(['/api/submit', '/submit'], upload.single('photo'), async (req, res) => {
  try {
    const data = req.body;
    const file = req.file;

    // Validate required fields
    if (!data.fullName || !data.email || !data.gender || !data.age || !data.country || !data.price30From || !data.price60From || !data.social1) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    data.hasAttachment = !!file;

    // Build attachment array
    const attachments = [];
    if (file) {
      attachments.push({
        filename: file.originalname,
        content: file.buffer,
      });
    }


    // Save to Google Sheets if configured
    if (process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && process.env.GOOGLE_PRIVATE_KEY && process.env.GOOGLE_SHEET_ID) {
      try {
        const serviceAccountAuth = new JWT({
          email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
          key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
          scopes: ['https://www.googleapis.com/auth/spreadsheets'],
        });

        const doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID, serviceAccountAuth);
        
        await doc.loadInfo(); 
        const sheet = doc.sheetsByIndex[0];

        // Check if email already exists
        const rows = await sheet.getRows();
        const existingRow = rows.find(row => {
          const rowEmail = row.get ? row.get('Email') : row['Email'];
          return rowEmail && rowEmail.toLowerCase() === data.email.toLowerCase();
        });

        if (existingRow) {
          return res.status(400).json({ error: 'An application with this email address has already been submitted.' });
        }
        
        // Ensure headers exist (for the blank sheet issue)
        await sheet.setHeaderRow([
          'Timestamp',
          'Full Name',
          'Email',
          'Phone',
          'Gender',
          'Age',
          'Country',
          '30s Video Price From ($)',
          '30s Video Price Till ($)',
          '60s Video Price From ($)',
          '60s Video Price Till ($)',
          'Social Media 1',
          'Social Media 2',
          'Social Media 3',
          'Portfoilo',
          'Notes'
        ]);

        // Add row
        await sheet.addRow({
          'Timestamp': new Date().toISOString(),
          'Full Name': data.fullName,
          'Email': data.email,
          'Phone': data.phone || '',
          'Gender': data.gender,
          'Age': data.age,
          'Country': data.country,
          '30s Video Price From ($)': data.price30From,
          '30s Video Price Till ($)': data.price30Till || 'Infinite',
          '60s Video Price From ($)': data.price60From,
          '60s Video Price Till ($)': data.price60Till || 'Infinite',
          'Social Media 1': data.social1,
          'Social Media 2': data.social2 || '',
          'Social Media 3': data.social3 || '',
          'Portfoilo': data.portfolio || '',
          'Notes': data.notes || ''
        });
        console.log('Successfully saved UGC application to Google Sheets');
      } catch (sheetError) {
        console.error('Error saving to Google Sheets:', sheetError);
        // Continue even if sheet fails
      }
    } else {
      console.log('Google Sheets credentials not found in environment.');
    }

    

    // 2. Send confirmation email to applicant
    const confirmEmail = await resend.emails.send({
      from: 'Idyll Productions <hiring@idyllproductions.work>',
      to: [data.email],
      subject: 'Application Received – UGC Creator',
      html: buildConfirmationEmailHTML(data.fullName),
    });

    console.log('Confirmation email sent:', confirmEmail);

    res.json({ 
      success: true, 
      message: 'Application submitted successfully',
      
      confirmEmailId: confirmEmail.data?.id,
    });

  } catch (error) {
    console.error('Submission error:', error);
    res.status(500).json({ 
      error: 'Failed to submit application. Please try again.',
      details: error.message 
    });
  }
});

// Serve the main page
app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Serve the UGC Creator Application page
app.get('/ugc', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'ugc.html'));
});

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`\n🚀 Idyll Productions Hiring Form running at http://localhost:${PORT}\n`);
  });
}

module.exports = app;
